# Generated by Django 4.0.1 on 2022-01-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RftFirmCode',
            fields=[
                ('frc_code', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, verbose_name='Код ГВЦ')),
                ('frct_ide', models.SmallIntegerField(choices=[(1, 'Экспедитор'), (2, 'ТГНЛ'), (3, 'Арендатор'), (4, 'Собственник')], verbose_name='Тип юр. лица')),
                ('okpo', models.CharField(db_index=True, max_length=10, verbose_name='ОКПО')),
                ('frm_short_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое наименование фирмы')),
                ('frm_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименоване фирмы')),
                ('update_date', models.DateTimeField(verbose_name='Дата обновления')),
            ],
            options={
                'db_table': 'RFT_FIRM_CODE',
            },
        ),
    ]
