# Generated by Django 4.0.1 on 2022-02-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0002_alter_rftfirmcode_options_rftfirmcode_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftCountry',
            fields=[
                ('cnt_ide', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код страны')),
                ('cnt_name', models.CharField(max_length=100, verbose_name='Наименование страны')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'RFT_COUNTRY',
                'ordering': ['cnt_ide'],
            },
        ),
    ]
