# Generated by Django 4.0.1 on 2022-02-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0004_rftoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftCargoEtsng',
            fields=[
                ('crg_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код грузы')),
                ('crg_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'db_table': 'RFT_CARGO_ETSNG',
                'ordering': ['crg_code'],
            },
        ),
    ]
