# Generated by Django 4.0.1 on 2022-02-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0005_rftcargoetsng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rftcountry',
            name='cnt_ide',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код страны'),
        ),
    ]
