# Generated by Django 4.0.1 on 2022-02-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0006_alter_rftcountry_cnt_ide'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftRailway',
            fields=[
                ('rlw_code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Код дороги')),
                ('rlw_name', models.CharField(max_length=3, verbose_name='Краткое наименование дороги')),
                ('rlw_full_name', models.CharField(max_length=100, verbose_name='Наименование дороги')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('cntr_ide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftcountry', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Дорога',
                'verbose_name_plural': 'Дороги',
                'db_table': 'RFT_RAILWAY',
                'ordering': ['rlw_name'],
            },
        ),
    ]
