# Generated by Django 4.0.1 on 2022-02-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0007_rftrailway'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftRlwDep',
            fields=[
                ('rdep_ide', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор отделения')),
                ('rdep_code', models.CharField(max_length=2, verbose_name='Код отделения')),
                ('rdep_name', models.CharField(max_length=100, verbose_name='Краткое наименование отделения')),
                ('rdep_full_name', models.CharField(max_length=100, verbose_name='Наименование отделения')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('rlw_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftrailway', verbose_name='Дорога')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'db_table': 'RFT_RLW_DEP',
                'ordering': ['rdep_ide'],
            },
        ),
    ]
