# Generated by Django 4.0.1 on 2022-02-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0009_alter_rftrailway_cntr_ide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rftrailway',
            name='cntr_ide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftcountry', verbose_name='Страна'),
        ),
    ]
