# Generated by Django 4.0.1 on 2022-02-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0010_alter_rftrailway_cntr_ide'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftStation',
            fields=[
                ('st_code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Код станции')),
                ('st_full_name', models.CharField(max_length=100, verbose_name='Наименование станции')),
                ('st_code_6', models.CharField(max_length=6, verbose_name='Код станции (6-символьный)')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('cntr_ide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftcountry', verbose_name='Страна')),
                ('rdep_ide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftrlwdep', verbose_name='Отделение')),
                ('rlw_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftrailway', verbose_name='Дорога')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
                'db_table': 'RFT_STATION',
                'ordering': ['st_code'],
            },
        ),
    ]
