# Generated by Django 4.0.1 on 2022-02-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0011_rftstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rftstation',
            name='rdep_ide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftrlwdep', verbose_name='Отделение'),
        ),
    ]
