# Generated by Django 4.0.1 on 2022-02-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0012_alter_rftstation_rdep_ide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rftstation',
            name='cntr_ide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftcountry', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='rftstation',
            name='rlw_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mc_references.rftrailway', verbose_name='Дорога'),
        ),
    ]
