# Generated by Django 4.0.1 on 2022-02-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0014_rftdepo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rftdepo',
            old_name='update_date',
            new_name='dp_update_date',
        ),
    ]
