# Generated by Django 4.0.1 on 2022-02-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0016_alter_rftdepo_dp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftRwcType',
            fields=[
                ('rt_code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Код рода вагона')),
                ('rt_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование рода вагона')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Род вагона',
                'verbose_name_plural': 'Роды вагонов',
                'db_table': 'RFT_RWC_TYPE',
                'ordering': ['rt_code'],
            },
        ),
    ]
