# Generated by Django 4.0.1 on 2022-02-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0017_rftrwctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rftrwctype',
            name='rt_name',
            field=models.CharField(max_length=100, verbose_name='Наименование рода вагона'),
        ),
    ]
