# Generated by Django 4.0.1 on 2022-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0019_rftrwcmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rftrwcmodel',
            name='rm_osob',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование модели вагона'),
        ),
    ]
