# Generated by Django 4.0.1 on 2022-02-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0021_rftconttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rftconttype',
            options={'ordering': ['ct_code'], 'verbose_name': 'Тип контейнера', 'verbose_name_plural': 'Типы контейнеров'},
        ),
        migrations.RenameField(
            model_name='rftconttype',
            old_name='rt_code',
            new_name='ct_code',
        ),
        migrations.RenameField(
            model_name='rftconttype',
            old_name='rt_name',
            new_name='ct_name',
        ),
    ]
