# Generated by Django 4.0.1 on 2022-03-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0023_rftrepairtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RwcFaultCause',
            fields=[
                ('cause_ide', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Код причины')),
                ('cause_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование причины')),
            ],
            options={
                'verbose_name': 'Причина неисправности',
                'verbose_name_plural': 'Причины неисправностей',
                'db_table': 'RWC_FAULT_CAUSE',
                'ordering': ['cause_ide'],
            },
        ),
    ]
