# Generated by Django 4.0.1 on 2022-03-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0024_rwcfaultcause'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftRwcFault',
            fields=[
                ('flt_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код неисправности')),
                ('flt_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование неисправности')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Неисправность',
                'verbose_name_plural': 'Неисправности',
                'db_table': 'RFT_RWC_FAULT',
                'ordering': ['flt_code'],
            },
        ),
    ]
