# Generated by Django 4.0.1 on 2022-03-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0025_rftrwcfault'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftServiceType',
            fields=[
                ('srvt_ide', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Код типа')),
                ('srvt_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование типа')),
            ],
            options={
                'verbose_name': 'Тип обслуживания',
                'verbose_name_plural': 'Типы обслуживания',
                'db_table': 'RFT_SERVICE_TYPE',
                'ordering': ['srvt_ide'],
            },
        ),
    ]
