# Generated by Django 4.0.1 on 2022-03-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0026_rftservicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftRwcCnd',
            fields=[
                ('cnd_code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Код состояния')),
                ('cnd_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование состояния')),
            ],
            options={
                'verbose_name': 'Состояние вагона',
                'verbose_name_plural': 'Состояния вагонов',
                'db_table': 'RFT_RWC_CND',
                'ordering': ['cnd_code'],
            },
        ),
    ]
