# Generated by Django 4.0.1 on 2022-03-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0027_rftrwccnd'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftRwcGroup',
            fields=[
                ('rwc_group', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код группы')),
                ('rwc_group_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование группы')),
                ('rwc_top_group', models.IntegerField(verbose_name='Код группы верхнего уровня')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('rwc_parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mc_references.rftrwcgroup', verbose_name='Код род. группы')),
            ],
            options={
                'verbose_name': 'Группа вагона',
                'verbose_name_plural': 'Группы вагонов',
                'db_table': 'RFT_RWC_GROUP',
                'ordering': ['rwc_group'],
            },
        ),
    ]
