# Generated by Django 4.0.1 on 2022-03-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0028_rftrwcgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rftrwcgroup',
            name='rwc_parent_group',
        ),
    ]
