# Generated by Django 4.0.1 on 2022-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0029_remove_rftrwcgroup_rwc_parent_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='rftrwcgroup',
            name='rwc_parent_group',
            field=models.IntegerField(default=0, verbose_name='Код род. группы'),
        ),
        migrations.AlterField(
            model_name='rftrwcgroup',
            name='rwc_top_group',
            field=models.IntegerField(default=0, verbose_name='Код группы верхнего уровня'),
        ),
    ]
