# Generated by Django 4.0.1 on 2022-03-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0030_rftrwcgroup_rwc_parent_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rftrwcgroup',
            name='rwc_group',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код группы'),
        ),
        migrations.AlterField(
            model_name='rftrwcgroup',
            name='rwc_parent_group',
            field=models.CharField(default='', max_length=10, verbose_name='Код род. группы'),
        ),
        migrations.AlterField(
            model_name='rftrwcgroup',
            name='rwc_top_group',
            field=models.CharField(default='', max_length=10, verbose_name='Код группы верхнего уровня'),
        ),
    ]
