# Generated by Django 4.0.1 on 2022-03-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_references', '0033_rftrwcowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RftContOwner',
            fields=[
                ('cont_owner_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код собственника')),
                ('cont_owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование собственника')),
            ],
            options={
                'verbose_name': 'Состояние вагона',
                'verbose_name_plural': 'Состояния вагонов',
                'db_table': 'RFT_CONT_OWNER',
                'ordering': ['cont_owner_code'],
            },
        ),
    ]
